### ISSUE TITLE
Not all main nav items are reachable on wide short screens

### ISSUE THREAD

**Issue by blnkt** [lsst-epo/rubin-obs-client#10] opened 2021-12-16 17:27 UTC
## Expected Behavior

Nav height should never exceed available window height and nav Items should scroll within the nav container.  This should be true on both mobile and desktop, for the high level nav items and nested nav items.

<img width="400" alt="Screen Shot 2021-12-16 at 9 48 46 AM" src="https://user-images.githubusercontent.com/8166060/146422929-c83f3e28-740f-4d38-b97b-596485a69704.png">

## Actual Behavior

Nav items at the bottom of the nav item lists are unreachable unless the user scrolls the page down to reveal those that are cut off.  

<img width="400" alt="Screen Shot 2021-12-16 at 9 48 34 AM" src="https://user-images.githubusercontent.com/8166060/146422870-11282625-3c64-4522-b796-12571dd35be3.png">

<img width="400" alt="Screen Shot 2021-12-16 at 9 48 13 AM" src="https://user-images.githubusercontent.com/8166060/146422877-45f5a7ed-2c6b-4a9e-b729-5c5e7faa045c.png">

## Steps to Reproduce the Problem

1. Set browser window to at least 1000px tall
2. Expand About dropdown in Main Header Nav
3. All nav items are in view
4. Set browser window to height < 800px
5. Expand About dropdown in Main Header Nav
6. Bottom most nav items are unreachable without scrolling entire page
7. Set browser window height to < 800px and width to < 1280px
8. Scroll to the top of the page or make Main Header sticky
8. Expand About dropdown in Main Header Nav
9. Nav container scrolls but bottom most items are unreachable without scrolling entire page or triggering hidden main header (unsticky-ifying it)#10 

## CIC Estimate
0 points

## How to fix
```css
.c-nav-list--desktop .c-subnav-list {
  max-height: calc(100vh - var(--header-height));
}
```

**Comment by dananjohnson** [comment] 2022-03-28 18:48
@blnkt I can't reproduce this, and suspect it may have been fixed by some of the work we did to address other issues with this nav. Can you see if it's still an issue for you?

**Comment by blnkt** [comment] 2022-03-29 00:03
I think this is still an issue.  I'm testing in Chrome: https://www.dropbox.com/s/twexck7w57btbsn/Screen%20Recording%202022-03-28%20at%204.59.28%20PM.mov?dl=0

**Comment by dananjohnson** [comment] 2022-03-29 16:21
Thanks, Blake. We'd fixed it for the mobile menu, I think, but not those desktop dropdowns.

**Closed** 2022-05-25 00:28 UTC
Labels: bug, nice-to-have
